### ISSUE TITLE
Add episode status tracking

### ISSUE THREAD

**Issue by ataias** [ataias/TorrentRSS#4]
Currently all rss items correspond to a series episode and they are added as "pending", which indicates they are pending to be watched. Someone may not be interested in watching everything from an RSS feed, so some updates are necessary:

- [ ] Create function to update episode status
- [ ] Update command line arguments to have two options:
  - [ ] Read feed and update db (sole option currently, it already does that)
  - [ ] Update specific episode status (new)

For updating the command line, using a command library might be interesting.
